if not Shibaz.HUD.Config["FastDL"] then return end

resource.AddFile("materials/shibaz/hud/ammo.png")
resource.AddFile("materials/shibaz/hud/armor.png")
resource.AddFile("materials/shibaz/hud/cleanup.png")
resource.AddFile("materials/shibaz/hud/crosshair.png")
resource.AddFile("materials/shibaz/hud/error.png")
resource.AddFile("materials/shibaz/hud/generic.png")
resource.AddFile("materials/shibaz/hud/health.png")
resource.AddFile("materials/shibaz/hud/hint.png")
resource.AddFile("materials/shibaz/hud/hunger.png")
resource.AddFile("materials/shibaz/hud/money.png")
resource.AddFile("materials/shibaz/hud/name.png")
resource.AddFile("materials/shibaz/hud/props.png")
resource.AddFile("materials/shibaz/hud/team.png")
resource.AddFile("materials/shibaz/hud/undo.png")
resource.AddFile("materials/shibaz/hud/speed.png")
resource.AddFile("materials/shibaz/hud/fuel.png")
resource.AddFile("materials/shibaz/hud/atm.png")
resource.AddFile("materials/shibaz/hud/owner.png")
resource.AddFile("resource/fonts/circular.ttf")
